### ISSUE TITLE
Task: Complete Network Request

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#51]
Allow users to input equations, send a POST request, and get an output with our server. 
#38

**Comment by DragonflyRobotics** [comment]
This task is working with CURL as of Thursday but @N1ks0n08 hasn't pushed because he is sick. The commit will be on dev soon.

**Comment by N1ks0n08** [comment]
e5a3b99f71f0e75ec8795d7dc46e709de94c24ac

The CURL request has been setup to correctly run on the Schedulers.io background thread to navigate around the Application Not Responding error. However, the CURL request was only able to be hard coded and user input will have to be implemented later due to sickness.

**Comment by DragonflyRobotics** [comment]
Something to note is that CURL only works on Android if the phone is rooted. We will need to take another look at the HTTP Java lib.
