### ISSUE TITLE
Task: Improve UI on Website

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#80]
Improve UI on Website by adding icons and adding the About Us. #6

**Comment by Hambreyola** [comment]
Modified the website code to include the website logo and the "About us" description. However, I could not test or commit due to CoderMerlin being down, which caused Vapor, the server that the website is running on, to also be down, which prevented me from testing the code. I will commit to the next sprint after spring break.

Added <img src="./Autodyff\ horizontal\ logo.png" alt="AutoDyff Logo" width="300" height=200"> 
Added description to "About us"

**Comment by DragonflyRobotics** [comment]
As a part of UI updates, I added a proper WYSIWIG editor that live renders math formula through Latex and MathJax. This was courtesy of the repository https://chungkwong.cc/equation-editor/equation-editor.html. I then converted the latex formula to the SymPy format and fixed a bunch of conflicting patterns like ** --> ^ and added a way to handle sqrt(x). Some functions remain unimplemented.

**Comment by Hambreyola** [comment]
I am having trouble solving merge conflicts, and I will ask for help and push the code as soon as possible.

**Comment by Hambreyola** [comment]
c96314b80e95f494983022bd06c21e05d66b44db
The most recent commit of the website (mathquill implementation) solves this issue.
